-- =========================================================
-- PANALOGIS - Script PostgreSQL para Supabase
-- Uso: despliegue cloud/demo en Vercel + Supabase
-- Nota academica: el script fuente del proyecto sigue siendo
-- database/panalogis.sql sobre MariaDB/MySQL.
-- =========================================================

SET client_encoding = 'UTF8';

DROP TABLE IF EXISTS factura CASCADE;
DROP TABLE IF EXISTS bitacora CASCADE;
DROP TABLE IF EXISTS mantenimiento CASCADE;
DROP TABLE IF EXISTS orden_servicio CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS rol_usuario CASCADE;
DROP TABLE IF EXISTS ruta CASCADE;
DROP TABLE IF EXISTS tipo_carga CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS conductor CASCADE;
DROP TABLE IF EXISTS vehiculo CASCADE;
DROP TABLE IF EXISTS tipo_vehiculo CASCADE;

DROP TYPE IF EXISTS vehiculo_estado_enum CASCADE;
DROP TYPE IF EXISTS conductor_estado_enum CASCADE;
DROP TYPE IF EXISTS cliente_estado_enum CASCADE;
DROP TYPE IF EXISTS usuario_estado_enum CASCADE;
DROP TYPE IF EXISTS orden_estado_enum CASCADE;
DROP TYPE IF EXISTS mantenimiento_tipo_enum CASCADE;
DROP TYPE IF EXISTS mantenimiento_estado_enum CASCADE;
DROP TYPE IF EXISTS factura_estado_enum CASCADE;
DROP TYPE IF EXISTS bitacora_operacion_enum CASCADE;

CREATE TYPE vehiculo_estado_enum AS ENUM ('ACTIVO', 'MANTENIMIENTO', 'INACTIVO');
CREATE TYPE conductor_estado_enum AS ENUM ('ACTIVO', 'INACTIVO', 'SUSPENDIDO');
CREATE TYPE cliente_estado_enum AS ENUM ('ACTIVO', 'INACTIVO');
CREATE TYPE usuario_estado_enum AS ENUM ('ACTIVO', 'INACTIVO');
CREATE TYPE orden_estado_enum AS ENUM ('PENDIENTE', 'EN_TRANSITO', 'ENTREGADO', 'CANCELADO');
CREATE TYPE mantenimiento_tipo_enum AS ENUM ('PREVENTIVO', 'CORRECTIVO', 'REVISION');
CREATE TYPE mantenimiento_estado_enum AS ENUM ('EN_PROCESO', 'COMPLETADO');
CREATE TYPE factura_estado_enum AS ENUM ('PENDIENTE', 'PAGADA', 'ANULADA');
CREATE TYPE bitacora_operacion_enum AS ENUM ('INSERT', 'UPDATE', 'DELETE');

CREATE TABLE tipo_vehiculo (
    id_tipo_vehiculo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion varchar(100) NOT NULL,
    capacidad_ton numeric(8, 2) NOT NULL
);

CREATE TABLE vehiculo (
    id_vehiculo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa varchar(20) NOT NULL UNIQUE,
    marca varchar(80) NOT NULL,
    modelo varchar(80) NOT NULL,
    anio smallint NOT NULL CHECK (anio BETWEEN 1900 AND 2100),
    id_tipo_vehiculo integer NOT NULL REFERENCES tipo_vehiculo(id_tipo_vehiculo),
    estado vehiculo_estado_enum NOT NULL DEFAULT 'ACTIVO',
    kilometraje numeric(10, 2) NOT NULL DEFAULT 0
);

CREATE TABLE conductor (
    id_conductor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula varchar(20) NOT NULL UNIQUE,
    nombre varchar(100) NOT NULL,
    apellido varchar(100) NOT NULL,
    telefono varchar(20),
    email varchar(150),
    licencia varchar(50) NOT NULL UNIQUE,
    categoria_licencia varchar(10) NOT NULL,
    vences_licencia date NOT NULL,
    estado conductor_estado_enum NOT NULL DEFAULT 'ACTIVO'
);

CREATE TABLE cliente (
    id_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc varchar(30) NOT NULL UNIQUE,
    razon_social varchar(200) NOT NULL,
    contacto_nombre varchar(150),
    contacto_tel varchar(20),
    contacto_email varchar(150),
    direccion text,
    estado cliente_estado_enum NOT NULL DEFAULT 'ACTIVO'
);

CREATE TABLE tipo_carga (
    id_tipo_carga integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(100) NOT NULL,
    refrigeracion boolean NOT NULL DEFAULT false,
    es_peligrosa boolean NOT NULL DEFAULT false,
    observaciones text
);

CREATE TABLE ruta (
    id_ruta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(150) NOT NULL,
    origen varchar(200) NOT NULL,
    destino varchar(200) NOT NULL,
    distancia_km numeric(8, 2),
    tiempo_est_horas numeric(5, 2),
    tarifa_base numeric(10, 2) NOT NULL
);

CREATE TABLE rol_usuario (
    id_rol integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(80) NOT NULL UNIQUE,
    descripcion text
);

CREATE TABLE usuario (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(80) NOT NULL UNIQUE,
    nombre_completo varchar(200) NOT NULL,
    email varchar(150) NOT NULL UNIQUE,
    id_rol integer NOT NULL REFERENCES rol_usuario(id_rol),
    estado usuario_estado_enum NOT NULL DEFAULT 'ACTIVO',
    fecha_creacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orden_servicio (
    id_orden integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_orden varchar(30) NOT NULL UNIQUE,
    fecha_creacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_programada date NOT NULL,
    id_cliente integer NOT NULL REFERENCES cliente(id_cliente),
    id_ruta integer NOT NULL REFERENCES ruta(id_ruta),
    id_vehiculo integer NOT NULL REFERENCES vehiculo(id_vehiculo),
    id_conductor integer NOT NULL REFERENCES conductor(id_conductor),
    id_tipo_carga integer NOT NULL REFERENCES tipo_carga(id_tipo_carga),
    peso_kg numeric(10, 2) NOT NULL,
    descripcion text,
    estado orden_estado_enum NOT NULL DEFAULT 'PENDIENTE',
    observaciones text
);

CREATE TABLE mantenimiento (
    id_mantenimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vehiculo integer NOT NULL REFERENCES vehiculo(id_vehiculo),
    tipo mantenimiento_tipo_enum NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    descripcion text NOT NULL,
    costo numeric(10, 2),
    taller varchar(200),
    estado mantenimiento_estado_enum NOT NULL DEFAULT 'EN_PROCESO'
);

CREATE TABLE factura (
    id_factura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_factura varchar(30) NOT NULL UNIQUE,
    id_orden integer NOT NULL UNIQUE REFERENCES orden_servicio(id_orden),
    fecha_emision timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subtotal numeric(12, 2) NOT NULL,
    impuesto numeric(12, 2) NOT NULL,
    total numeric(12, 2) NOT NULL,
    estado factura_estado_enum NOT NULL DEFAULT 'PENDIENTE',
    fecha_pago date
);

CREATE TABLE bitacora (
    id_bitacora integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada varchar(100) NOT NULL,
    operacion bitacora_operacion_enum NOT NULL,
    id_registro integer NOT NULL,
    descripcion text,
    fecha_operacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario integer REFERENCES usuario(id_usuario)
);

CREATE OR REPLACE FUNCTION fn_check_conductor_libre()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM orden_servicio
        WHERE id_conductor = NEW.id_conductor
          AND estado IN ('PENDIENTE', 'EN_TRANSITO')
    ) THEN
        RAISE EXCEPTION 'El conductor ya tiene una orden activa asignada.' USING ERRCODE = 'P0001';
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_check_vehiculo_disponible()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM vehiculo
        WHERE id_vehiculo = NEW.id_vehiculo
          AND estado = 'MANTENIMIENTO'
    ) THEN
        RAISE EXCEPTION 'El vehículo está en mantenimiento y no puede operar.' USING ERRCODE = 'P0001';
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_generar_factura()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_tarifa numeric(10, 2);
    v_subtotal numeric(12, 2);
    v_num varchar(30);
BEGIN
    IF NEW.estado = 'ENTREGADO' AND OLD.estado IS DISTINCT FROM 'ENTREGADO' THEN
        SELECT tarifa_base
        INTO v_tarifa
        FROM ruta
        WHERE id_ruta = NEW.id_ruta;

        v_subtotal := v_tarifa * (NEW.peso_kg / 1000);
        v_num := 'FAC-' || EXTRACT(YEAR FROM CURRENT_DATE)::int || '-' || LPAD(NEW.id_orden::text, 6, '0');

        INSERT INTO factura (numero_factura, id_orden, subtotal, impuesto, total)
        VALUES (v_num, NEW.id_orden, v_subtotal, v_subtotal * 0.07, v_subtotal * 1.07)
        ON CONFLICT (id_orden) DO NOTHING;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_bitacora_orden()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.estado IS DISTINCT FROM NEW.estado THEN
        INSERT INTO bitacora (tabla_afectada, operacion, id_registro, descripcion)
        VALUES (
            'ORDEN_SERVICIO',
            'UPDATE',
            NEW.id_orden,
            'Estado cambio de [' || OLD.estado || '] a [' || NEW.estado || ']'
        );
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_vehiculo_a_mantenimiento()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.estado = 'EN_PROCESO' THEN
        UPDATE vehiculo
        SET estado = 'MANTENIMIENTO'
        WHERE id_vehiculo = NEW.id_vehiculo;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_vehiculo_liberado()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.estado = 'COMPLETADO' AND OLD.estado = 'EN_PROCESO' THEN
        UPDATE vehiculo
        SET estado = 'ACTIVO'
        WHERE id_vehiculo = NEW.id_vehiculo;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_check_conductor_libre
BEFORE INSERT ON orden_servicio
FOR EACH ROW
EXECUTE FUNCTION fn_check_conductor_libre();

CREATE TRIGGER trg_check_vehiculo_disponible
BEFORE INSERT ON orden_servicio
FOR EACH ROW
EXECUTE FUNCTION fn_check_vehiculo_disponible();

CREATE TRIGGER trg_generar_factura
AFTER UPDATE ON orden_servicio
FOR EACH ROW
EXECUTE FUNCTION fn_generar_factura();

CREATE TRIGGER trg_bitacora_orden
AFTER UPDATE ON orden_servicio
FOR EACH ROW
EXECUTE FUNCTION fn_bitacora_orden();

CREATE TRIGGER trg_vehiculo_a_mantenimiento
AFTER INSERT ON mantenimiento
FOR EACH ROW
EXECUTE FUNCTION fn_vehiculo_a_mantenimiento();

CREATE TRIGGER trg_vehiculo_liberado
AFTER UPDATE ON mantenimiento
FOR EACH ROW
EXECUTE FUNCTION fn_vehiculo_liberado();

CREATE OR REPLACE FUNCTION sp_crear_orden(
    p_fecha_prog date,
    p_id_cliente integer,
    p_id_ruta integer,
    p_id_vehiculo integer,
    p_id_conductor integer,
    p_id_tipo_carga integer,
    p_peso_kg numeric(10, 2),
    p_descripcion text
)
RETURNS TABLE (numero_orden varchar(30), mensaje varchar(200))
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_orden integer;
BEGIN
    v_id_orden := nextval(pg_get_serial_sequence('orden_servicio', 'id_orden'));
    numero_orden := 'ORD-' || EXTRACT(YEAR FROM CURRENT_DATE)::int || '-' || LPAD(v_id_orden::text, 6, '0');

    INSERT INTO orden_servicio (
        id_orden,
        numero_orden,
        fecha_programada,
        id_cliente,
        id_ruta,
        id_vehiculo,
        id_conductor,
        id_tipo_carga,
        peso_kg,
        descripcion
    )
    VALUES (
        v_id_orden,
        numero_orden,
        p_fecha_prog,
        p_id_cliente,
        p_id_ruta,
        p_id_vehiculo,
        p_id_conductor,
        p_id_tipo_carga,
        p_peso_kg,
        p_descripcion
    );

    mensaje := 'Orden creada exitosamente: ' || numero_orden;
    RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION sp_rentabilidad_ruta(
    p_anio integer,
    p_mes integer
)
RETURNS TABLE (
    ruta varchar(150),
    origen varchar(200),
    destino varchar(200),
    total_servicios bigint,
    ingresos_netos numeric,
    itbms_cobrado numeric,
    ingresos_totales numeric,
    promedio_por_servicio numeric
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        r.nombre::varchar(150) AS ruta,
        r.origen::varchar(200),
        r.destino::varchar(200),
        COUNT(o.id_orden) AS total_servicios,
        SUM(f.subtotal) AS ingresos_netos,
        SUM(f.impuesto) AS itbms_cobrado,
        SUM(f.total) AS ingresos_totales,
        AVG(f.total) AS promedio_por_servicio
    FROM ruta r
    JOIN orden_servicio o ON o.id_ruta = r.id_ruta
    JOIN factura f ON f.id_orden = o.id_orden
                 AND f.estado <> 'ANULADA'
    WHERE o.estado = 'ENTREGADO'
      AND (p_anio IS NULL OR EXTRACT(YEAR FROM o.fecha_programada) = p_anio)
      AND (p_mes IS NULL OR EXTRACT(MONTH FROM o.fecha_programada) = p_mes)
    GROUP BY r.id_ruta, r.nombre, r.origen, r.destino
    ORDER BY ingresos_totales DESC;
END;
$$;

INSERT INTO rol_usuario (nombre, descripcion) VALUES
    ('ADMINISTRADOR', 'Acceso total al sistema'),
    ('OPERADOR', 'Lectura y escritura en tablas operativas'),
    ('CONSULTOR', 'Solo lectura para reportes');

INSERT INTO tipo_vehiculo (descripcion, capacidad_ton) VALUES
    ('Camión liviano', 3.50),
    ('Camión mediano', 10.00),
    ('Trailer / Semirremolque', 30.00),
    ('Furgón refrigerado', 8.00);

INSERT INTO vehiculo (placa, marca, modelo, anio, id_tipo_vehiculo) VALUES
    ('AB-1234', 'Mercedes-Benz', 'Actros 1845', 2020, 3),
    ('CD-5678', 'Hino', '300 Series', 2021, 2),
    ('EF-9012', 'Isuzu', 'NQR 75L', 2019, 2),
    ('GH-3456', 'Volkswagen', 'Constellation', 2022, 3),
    ('IJ-7890', 'Hyundai', 'HD78', 2020, 2),
    ('KL-1122', 'Mitsubishi', 'Canter FE84', 2021, 1),
    ('MN-3344', 'Volvo', 'FH16 750', 2023, 3);

INSERT INTO conductor (cedula, nombre, apellido, licencia, categoria_licencia, vences_licencia, telefono) VALUES
    ('8-123-456', 'Carlos', 'Mendoza', 'LIC-001', 'C3', '2027-06-30', '6700-1111'),
    ('8-234-567', 'Roberto', 'Flores', 'LIC-002', 'C3', '2026-12-15', '6700-2222'),
    ('8-345-678', 'Luis', 'Samaniego', 'LIC-003', 'C2', '2027-03-22', '6700-3333'),
    ('8-456-789', 'Ana', 'Reyes', 'LIC-004', 'C2', '2026-08-10', '6700-4444'),
    ('8-567-890', 'Pedro', 'Castillo', 'LIC-005', 'C3', '2027-11-05', '6700-5555');

INSERT INTO cliente (ruc, razon_social, contacto_nombre, contacto_tel, contacto_email) VALUES
    ('123-456-1-2026', 'Constructora Panamá S.A.', 'Ana Rodríguez', '6800-1234', 'ana@constructora.pa'),
    ('789-012-1-2026', 'Supermercados Central S.A.', 'Marcos León', '6800-5678', 'marcos@central.pa'),
    ('345-678-1-2026', 'Farmacéutica Istmo S.A.', 'Rosa Díaz', '6800-9012', 'rosa@farmistmo.pa'),
    ('901-234-1-2026', 'Cementos Nacionales S.A.', 'Jorge Pérez', '6800-3456', 'jorge@cementos.pa'),
    ('567-890-1-2026', 'Distribuidora Tech Panama S.A.', 'Karla Mora', '6800-7890', 'karla@techpanama.pa');

INSERT INTO tipo_carga (nombre, refrigeracion, es_peligrosa) VALUES
    ('Materiales de construcción', false, false),
    ('Alimentos perecederos', true, false),
    ('Medicamentos', true, false),
    ('Carga general seca', false, false),
    ('Maquinaria industrial', false, false);

INSERT INTO ruta (nombre, origen, destino, distancia_km, tiempo_est_horas, tarifa_base) VALUES
    ('Ciudad - Colón', 'Ciudad de Panamá', 'Colón', 76, 1.5, 150.00),
    ('Ciudad - Chiriquí', 'Ciudad de Panamá', 'David, Chiriquí', 480, 6.0, 850.00),
    ('Ciudad - Penonomé', 'Ciudad de Panamá', 'Penonomé', 148, 2.5, 280.00),
    ('Ciudad - Santiago', 'Ciudad de Panamá', 'Santiago', 250, 3.5, 420.00),
    ('Ciudad - Azuero', 'Ciudad de Panamá', 'Los Santos', 310, 4.5, 520.00);

INSERT INTO usuario (username, nombre_completo, email, id_rol) VALUES
    ('admin', 'Administrador PanaLogis', 'admin@panalogis.pa', 1);

UPDATE vehiculo
SET kilometraje = CASE id_vehiculo
    WHEN 1 THEN 185420.50
    WHEN 2 THEN 94215.20
    WHEN 3 THEN 131880.75
    WHEN 4 THEN 68240.10
    WHEN 5 THEN 118995.40
    WHEN 6 THEN 156700.00
    WHEN 7 THEN 213450.90
END;

UPDATE conductor
SET email = CASE id_conductor
    WHEN 1 THEN 'carlos.mendoza@panalogis.pa'
    WHEN 2 THEN 'roberto.flores@panalogis.pa'
    WHEN 3 THEN 'luis.samaniego@panalogis.pa'
    WHEN 4 THEN 'ana.reyes@panalogis.pa'
    WHEN 5 THEN 'pedro.castillo@panalogis.pa'
END;

UPDATE cliente
SET direccion = CASE id_cliente
    WHEN 1 THEN 'Parque Logístico Este, Panamá'
    WHEN 2 THEN 'Zona Comercial Colón 2000, Colón'
    WHEN 3 THEN 'Ciudad de la Salud, Panamá'
    WHEN 4 THEN 'Parque Industrial La Chorrera, Panamá Oeste'
    WHEN 5 THEN 'Área Bancaria, Ciudad de Panamá'
END;

SELECT * FROM sp_crear_orden('2026-04-10', 1, 1, 1, 1, 1, 12000.00, 'Traslado de acero estructural');
UPDATE orden_servicio
SET estado = 'ENTREGADO',
    observaciones = 'Entrega completada y cerrada sin incidencias operativas.'
WHERE numero_orden = 'ORD-2026-000001';
UPDATE factura
SET estado = 'PAGADA',
    fecha_pago = '2026-04-11'
WHERE id_orden = (SELECT id_orden FROM orden_servicio WHERE numero_orden = 'ORD-2026-000001');

SELECT * FROM sp_crear_orden('2026-04-09', 2, 2, 2, 2, 2, 8500.00, 'Carga refrigerada para cadena de supermercados');
UPDATE orden_servicio
SET estado = 'EN_TRANSITO',
    observaciones = 'Unidad salió a las 06:30 y reportó paso por Capira.'
WHERE numero_orden = 'ORD-2026-000002';

SELECT * FROM sp_crear_orden('2026-04-05', 3, 3, 3, 3, 3, 2400.00, 'Medicamentos con cadena de frío');
UPDATE orden_servicio
SET estado = 'ENTREGADO',
    observaciones = 'Entrega hospitalaria completada sin incidencias.'
WHERE numero_orden = 'ORD-2026-000003';

SELECT * FROM sp_crear_orden('2026-04-06', 4, 4, 4, 4, 5, 18000.00, 'Maquinaria para planta de cemento');
UPDATE orden_servicio
SET estado = 'ENTREGADO',
    observaciones = 'Entrega cerrada, pero la factura quedó anulada por ajuste comercial.'
WHERE numero_orden = 'ORD-2026-000004';
UPDATE factura
SET estado = 'ANULADA',
    fecha_pago = NULL
WHERE id_orden = (SELECT id_orden FROM orden_servicio WHERE numero_orden = 'ORD-2026-000004');

SELECT * FROM sp_crear_orden('2026-04-04', 1, 5, 5, 3, 4, 4300.00, 'Carga seca para distribución regional');
UPDATE orden_servicio
SET estado = 'CANCELADO',
    observaciones = 'Cliente reprogramó la descarga para la próxima semana.'
WHERE numero_orden = 'ORD-2026-000005';

SELECT * FROM sp_crear_orden('2026-04-03', 2, 1, 4, 4, 4, 3600.00, 'Reposición urgente de mercancía seca');
UPDATE orden_servicio
SET observaciones = 'Pendiente de salida en cuanto se libere la ventana de carga.'
WHERE numero_orden = 'ORD-2026-000006';

INSERT INTO mantenimiento (
    id_vehiculo, tipo, fecha_inicio, fecha_fin, descripcion, costo, taller, estado
) VALUES
    (5, 'CORRECTIVO', '2026-04-08', NULL, 'Reemplazo del sistema de frenos neumáticos', 1850.00, 'Taller Industrial Pacífico', 'EN_PROCESO'),
    (7, 'PREVENTIVO', '2026-03-18', '2026-03-19', 'Cambio de filtros, fluidos y calibración general', 420.00, 'Centro Técnico Norte', 'COMPLETADO');

UPDATE vehiculo SET estado = 'INACTIVO' WHERE id_vehiculo = 7;
UPDATE conductor SET estado = 'SUSPENDIDO' WHERE id_conductor = 5;
UPDATE cliente SET estado = 'INACTIVO' WHERE id_cliente = 5;

-- =========================================================
-- FIN - Supabase/PostgreSQL listo para demo
-- =========================================================
